import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { renderMarkToAnsi } from './render.js';
import { defaultAnsiRegistry } from './components/index.js';

/**
 * The nesting-regression acceptance test (post-phase-2 review): a card
 * nested in a card, a row nested in a card, a card nested in a callout, and
 * a plain paragraph inside a card must all lay out exactly as the
 * PUBLISHED, pre-Ink 0.15.0 engine laid them out — the known-good behavior
 * the fixtures under `test-fixtures/` were generated from. Deliberately
 * NOT under `conformance/render/` and NOT regenerated by this engine: these
 * are an independently-sourced acceptance target, not a fixture this
 * engine's own regenerate script owns.
 */

const here = fileURLToPath(new URL('.', import.meta.url));
const FIXTURES_DIR = join(here, '..', 'test-fixtures');

const WIDTHS = [60, 80, 100] as const;

describe('nesting regression: byte-identical to the pre-Ink engine at each width', () => {
  const source = readFileSync(join(FIXTURES_DIR, 'nesting.mk.md'), 'utf8');

  for (const width of WIDTHS) {
    it(`width ${width}`, async () => {
      const expected = readFileSync(
        join(FIXTURES_DIR, `nesting-${width}.txt`),
        'utf8',
      );
      const actual = await renderMarkToAnsi(
        source,
        defaultAnsiRegistry,
        undefined,
        undefined,
        { width, color: 'never' },
      );
      expect(actual).toBe(expected);
    });
  }
});

/**
 * The tabs/details regression (a second post-phase-2 review round): the
 * string-mode `tabs` heading and `tab.ts`'s own component were BOTH
 * printing a tab's label — `tabs` draws the heading itself
 * (`render.tsx`'s `extractTabPanels`/`extractTabPanelsElement`), so a `tab`
 * child's body must be rendered from its own INNER children only, never by
 * re-rendering the whole `tab` directive a second time. Covers `tabs` and
 * `details` at the top level and nested inside a `card`, at widths 60 and
 * 80. Same independently-sourced-fixture rule as the nesting suite above:
 * generated from the published pre-Ink 0.15.0 engine, not regenerated or
 * edited here.
 */
describe('tabs/details regression: byte-identical to the pre-Ink engine at each width', () => {
  const source = readFileSync(join(FIXTURES_DIR, 'tabs-details.mk.md'), 'utf8');

  for (const width of [60, 80] as const) {
    it(`width ${width}`, async () => {
      const expected = readFileSync(
        join(FIXTURES_DIR, `tabs-details-${width}.txt`),
        'utf8',
      );
      const actual = await renderMarkToAnsi(
        source,
        defaultAnsiRegistry,
        undefined,
        undefined,
        { width, color: 'never' },
      );
      expect(actual).toBe(expected);
    });
  }
});
